In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data/data.xlsx')

In [3]:
df

,Unnamed: 0,ดัชนีการลงทุนภาคเอกชน,X1 หนี้รัฐบาล,X2 หนี้รัฐวิสาหกิจ,X3 หนี้รัฐวิสาหกิจที่ทำธุรกิจในภาคการเงิน (รัฐบาลค้ำประกัน),X4 หนี้หน่วยงานรัฐ,X5 ดัชนีความเชื่อมั่นผู้บริโภค
0,2556-01-01 00:00:00,121.9,3531418.63,1066503.28,202267.50,6953.53,33.1
1,2556-02-01 00:00:00,118.9,3555634.61,1072414.05,203271.11,8053.53,32.4
2,2556-03-01 00:00:00,131.8,3563398.53,1069302.32,204270.91,5561.91,37.9
3,2556-04-01 00:00:00,117.2,3589728.39,1060180.28,213508.27,3383.37,42.2
4,2556-05-01 00:00:00,126.5,3609170.92,1065687.08,214507.48,813.37,20.1
...,...,...,...,...,...,...,...
127,2566-08-01 00:00:00,132.7,9676757.05,1075590.65,501363.31,61124.84,53.4
128,2566-09-01 00:00:00,130.1,9779786.75,1076922.26,501461.57,61416.92,55.7
129,2566-10-01 00:00:00,143.9,9779797.23,1079735.23,493652.23,61624.71,55.8
130,2566-11-01 00:00:00,156.2,9780061.01,1076508.49,437874.37,71757.68,55.0
131,2566-12-01 00:00:00,140.4,9726709.15,1073853.66,438465.57,81746.76,54.8